[package]
name = "backend"
version = "0.1.0"
edition = "2025"

[dependencies]
axum = "0.8.1"
tokio = { version = "1.44.1", features = ["full"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tower-http = { version = "0.6.2", features = ["cors"] }